name: Build and Deploy
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: angular process
              uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
              with:
                github_access_token: ${{ secrets.GH_TOKEN }}
                build_configuration: production
                base_href: /VtuberRPG/
                angular_dist_build_folder: dist/vtuber-rpg/browser

permissions:
    contents: write